repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the latest version
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/psf/black
    rev: 24.1.1  # Use the latest version
    hooks:
    -   id: black
        language_version: python3.12  # Your Python version
