[tool.poetry]
name = "career-crew"
version = "0.1.0"
description = "AI agents that help advance my career."
authors = ["Nerijus Masikonis <nerijus@masikonis.lt>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
langchain = "^0.3.12"
langchain-core = "^0.3.25"
langchain-community = "^0.3.12"
langchain-openai = "^0.2.12"
langgraph = "^0.2.59"
python-dotenv = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
