name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  # Checkout the PR branch
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install dependencies
        run: poetry run poetry install --no-interaction --no-root --only dev

      - name: Fix Import Sorting
        run: poetry run isort .

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: sort imports with isort"
          file_pattern: "*.py"